### ISSUE TITLE
Problems installing in NextJS

### ISSUE THREAD

**Issue by annaLucian** [nuxy/react-baraja-js#2]
After install with `npm`, throw me this error:
I think is related with Proptypes. I hope you can fix it. 

![image](https://github.com/nuxy/react-baraja-js/assets/69244265/1705a106-907b-4b9e-943d-09f283224f62)

**Comment by nuxy** [comment]
@annaLucian The dependency in question is only installed in development mode (e.g. `--omit=dev`)

I deployed [an update](https://github.com/nuxy/react-baraja-js/commit/c22b1d4a13b501413b43088f10acf0ca4797ec04) that moves this library into the `dependencies` scope to resolve Next.js installs.
